baseURL = "https://dopaminegirl19.github.io/"
languageCode = "en-us"
title = "morgane moss"
theme="archie"
copyright = "© Morgane Moss"
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
[params]
	mode="auto"
	useCDN=false

[[menu.main]]
name = "projects"
url = "/projects"
weight = 1